### PR TITLE
Downgrade startup ini errors to warnings

### PR DESCRIPTION
**Pull request by Xiaoxun92**
This PR resolves [Downgrade startup ini errors to warnings](https://github.com/1dot13/source/issues/7)

### CODE REVIEW

**Comment by rftrdev** [comment]
This looks fine, but can you post a screenshot of how this looks?

**Comment by Xiaoxun92** [comment]
Sure! Here is the screenshot:
image

The text took ~14s to disappear on my old Alienware laptop loading from an HDD. Might be faster on a better device. But either way, the `for` loop I deleted didn't help extend the visible time because the text only appeared after the loop finished running.

**Comment by rftrdev** [comment]
If you wanna do a follow up investigation as to why the same error is printed twice that'd be swell (but no pressure 🙂)

**Comment by Xiaoxun92** [comment]
I noticed that as well and investigated it a bit :)

The same error message was generated in 2 places on startup:
1. InitializeGame -> LoadGameExternalOptions
2. InitializeGame -> LoadFeatureFlags -> UpdateFeatureFlags -> LoadGameExternalOptions

Any suggestions on how to improve it?

**Pull request merged**
